### ISSUE TITLE
Use Queries rather than routes for parameters

### ISSUE THREAD

**Issue by da3dsoul** [maxpiva/Nancy.Rest.Module#1]
I'm running across issues where an empty string causes url corruption

**Comment by da3dsoul** [comment]
They will need to be URLEncoded for strings as well.

**Comment by maxpiva** [comment]
Well urlencode is for the querystring not for rest paths, last time i check you must not use urlencode on rest paths. I'll figure something out... since the support encoding in the paths is kinda gray area.

**Comment by da3dsoul** [comment]
When you pass unsafe characters to a method in rest.client, it returns 404. IDK what really needs to be done, but that needs to be fixed somehow. We could do a json post with the method as the route and parameters in the post

**Comment by maxpiva** [comment]
editing the Rest attribute should be the safest best, anyway, letme try to
fix it anyway.

**Comment by da3dsoul** [comment]
I've not had any issues regarding this in a while
